### PR TITLE
refactor(cli): interactive mode with clack

### PR DESCRIPTION
**Pull request by astahmer**
## 📝 Description

Screenshot 2023-07-21 at 00 18 00

## 💣 Is this a breaking change (Yes/No):

no, opt-in with -i flag

### CODE REVIEW

**Comment by anubra266** [comment]
CleanShot 2023-07-30 at 01 20 35@2x

This is only for CLI, so I'm thinking we could just show it only when user does not choose postcss;

**Comment by segunadebayo** [comment]
What’s left to get this in? @astahmer

I would say let’s set interactive flag to false by default to keep the current workflow, and make it an opt in.

Other than that, it looks good to me.

**Comment by astahmer** [comment]
I think other than a ascii logo that we discussed, it's ready
got it, will rebase, revert the breaking change and make it opt-in instead

**Comment by astahmer** [comment]
@anubra266 good points but let's do that in another PR, this is a bit unrelated

**Comment by anubra266** [comment]
May we document the interactive flag.
https://panda-css.com/docs/references/cli#flags
https://panda-css.com/docs/installation/cli

**Pull request merged**
