### PR TITLE
fix(postcss): regression with user-defined rules not reloaded and kill astro plugin

### PR DESCRIPTION
**Pull request by astahmer**
Closes https://github.com/chakra-ui/panda/issues/1955

## 📝 Description

BREAKING: Remove the `@pandacss/astro` plugin in favor of just using the `postcss` plugin

Fix `@pandacss/postcss` plugin regression when the entry CSS file (with `@layer` rules order) contains user-defined
rules, those user-defined rules would not be reloaded correctly after being changed. (This was due to a `@pandacss/astro` specific fix that affected users of the postcss plugin)

---

Fix an edge-case for when the `config.outdir` would not be set in the `panda.config`

Internal details: The `outdir` would not have any value after a config change due to the fallback being set in the
initial config resolving code path but not in context reloading code path, moving it inside the config loading function
fixes this issue.

## 💣 Is this a breaking change (Yes/No):

YES if you're using the `@pandacss/astro` plugin please migrate to just using the `@pandacss/postcss` plugin (you don't have to install anything, it's included with in `@pandacss/dev/postcss`) by taking [these steps](https://panda-css.com/docs/installation/vite#configure-the-entry-css-with-layers):

1. Remove the `@pandacss/astro` plugin usage from your `astro.config`
2. Configure the entry CSS with layers: create a `.css` file (or to an existing one) the `@layer` rules order (which was implicitly added by the `@pandacss/astro` before): `@layer reset, base, tokens, recipes, utilities;`, 
3. make sure to import this `.css` file (new or existing) somewhere in your app, it makes sense to add it in a `layout.astro` file

## 📝 Additional Information

the `@pandacss/astro` had little value, it was only a wrapper of the `@pandacss/postcss` plugin and only allowed to skip 1 step: importing a `.css` file with the `@layer` rules.
it created unnecessary maintenance (like the issue linked above) and specific tweaks were needed to make it work seamlessly that also affected other (non-astro) `postcss` users

### CODE REVIEW

**Comment by kristojorg** [comment]
Nice, thank you!

**Comment by kristojorg** [comment]
Can you tell me if this has been released? I am still seeing this bug. I specifically need to add a layer to my layer order and am unable to get panda to work when doing this:
```
@layer reset, ionic, base, tokens, recipes, utilities;
```

**Comment by anubra266** [comment]
@kristojorg what method are you using to setup panda, and it would be helpful if you could attach a reproduction

**Comment by kristojorg** [comment]
@anubra266 I have failed to reproduce on my reproduction stackblitz from my previous ticket with the newest panda package. I will debug my local setup and if I can reproduce, I'll open a new issue

**Comment by Omikorin** [comment]
@kristojorg did you add postcss config from [these docs](https://panda-css.com/docs/installation/astro#update-the-postcss-config)? For me, it was a must-have to get CSS working again.

**Pull request merged**
